### ISSUE TITLE
Linking problem with ghc 7.8.2 winx64

### ISSUE THREAD

**Issue by Twinside** [bsl/bindings-GLFW#11]
Hello,

While trying to compile the test suite (or any other library depending on bindings-GLFW), I obtain the following error:

    [1 of 1] Compiling Bindings.GLFW    ( dist\build\Bindings\GLFW.hs, dist\build\Bindings\GLFW.o )
    [1 of 1] Compiling Bindings.GLFW    ( dist\build\Bindings\GLFW.hs, dist\build\Bindings\GLFW.p_o )
    In-place registering bindings-GLFW-3.0.3.2...
    Preprocessing test suite 'main' for bindings-GLFW-3.0.3.2...
    [1 of 1] Compiling Main             ( Test.hs, dist\build\main\main-tmp\Main.o )
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    Loading package base ... linking ... done.
    Loading package bindings-DSL-1.0.21 ... linking ... done.
    Loading package bindings-GLFW-3.0.3.2 ... linking ... ghc.exe: warning: _vsnprintf from msvcrt is linked instead of __imp__vsnprintf
    ghc.exe: C:\Users\Vince\Documents\Coding\bindings-GLFW\dist\build\HSbindings-GLFW-3.0.3.2.o: unknown symbol `strdup'
    ghc.exe: unable to load package `bindings-GLFW-3.0.3.2'

Here some version of the software I'm using:

    [15:54:13] ~/Documents/Coding/bindings-GLFW> ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.2
    [15:54:20] ~/Documents/Coding/bindings-GLFW> ghc --print-target-platform
    x86_64-unknown-mingw32
    [15:54:25] ~/Documents/Coding/bindings-GLFW> ghc --print-build-platform
    x86_64-unknown-mingw32
    [15:54:29] ~/Documents/Coding/bindings-GLFW> cabal --version
    cabal-install version 1.20.0.2
    using version 1.20.0.0 of the Cabal library

Is there any working around for this problem?

   Thanks

**Comment by schell** [comment]
I'm pretty sure this is fixed.

**Comment by Delli** [comment]
same linking problem unknow symbol "strdup " 

d\Graphics\UI\GLFW\Types.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package bindings-DSL-1.0.22 ... linking ... done.
Loading package bindings-GLFW-3.1.1.2 ... linking ... ghc.exe: unable to load pa
ckage `bindings-GLFW-3.1.1.2'
ghc.exe: warning: _vsnprintf from msvcrt is linked instead of __imp__vsnprintf
ghc.exe: C:\Users\rudy\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\bindings-G
LFW-3.1.1.2\HSbindings-GLFW-3.1.1.2.o: unknown symbol `strdup'
cabal: Error: some packages failed to install:
GLFW-b-1.4.7.2 failed during the building phase. The exception was:
ExitFailure 1

B:\haskell>ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

B:\haskell>ghc --print-target-platform
x86_64-unknown-mingw32

B:\haskell>ghc --print-build-platform
x86_64-unknown-mingw32

B:\haskell>cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.3 of the Cabal library
